// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2905fd8e181cd2f4083a615fa51f1913)
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		// 添加 R2 bucket 绑定
		MEDIA: R2Bucket;
	}
}
interface Env extends Cloudflare.Env {}
